# test configuration for scanwatch

#filter = "*.pdf"

[[rules]]
path = "./test"
cmd = "xpdf"
args = ["{filename}"]
msg = "opening '{filename}' with xpdf"
x = ""

[[rules]]
path = "./test"
cmd = "lpr"
args = ["-P{x}", "{filename}"]
msg = "sending '{filename}' to printer '{x}'"
x = "kyo_einseitig"
