# sample configuration file for `scanwatch`
# for details on the .toml file format, see https://toml.io/

#filter = "*.pdf"

[rules.xpdf]
path = "test"
cmd = "xpdf"
args = ["{filename}"]
msg = "opening '{filename:short}' with xpdf"
x = ""

[rules.lpr]
path = "test-lpr"
cmd = "echo"
#cmd = "lpr"  # disabled, so that during testing we do not print all the time
args = ["-P{x}", "{filename}"]
msg = "sending '{filename}' to printer '{x}'"
x = "kyo_einseitig"
