# sample configuration file for `scanwatch`
# for details on the .toml file format, see https://toml.io/

#filter = "*.pdf"

path = "test"

[rules.xpdf]
cmd = "xpdf"
args = ["{filename}"]
msg = "opening '{filename:short}' with xpdf"

[rules.lpr]
cmd = "echo"
#cmd = "lpr"  # disabled, so that during testing we do not print all the time
args = ["-Pkyo_einseitig", "{filename}"]
msg = "sending '{filename}' to printer 'kyo_einseitig'"
