# sample configuration file for `scanwatch`
# for details on the .toml file format, see https://toml.io/

path ="~/scanwatch"

[rules.xpdf]
filter = "\\.pdf$"
icon = "application-pdf"
cmd = "xpdf"
args = ["{filename}"]
msg = "opening '{filename:short}' with xpdf"

[rules.lpr]
filter = "^CN.*\\.pdf$"
icon = "printer"
cmd = "echo"
#cmd = "lpr"  # disabled, so that during testing we do not print all the time
args = ["-P{x}", "{filename}"]
msg = "sending '{filename:short}' to printer '{x}'"
x = "kyo_einseitig"
