# sample configuration file for `scanwatch`
# for details on the .toml file format, see https://toml.io/

# global path to be watched. Only one path per instance.
path = "test"

[rules.xpdf]
ends_with = ".pdf" # match any pdf file
cmd = "xpdf"
args = ["{filename}"]
msg = "opening '{filename:short}' with xpdf"

[rules.lpr]
ends_with = ".pdf"
starts_with = "CN" # prefix given by scanner software
cmd = "echo"
#cmd = "lpr"  # disabled, so that during testing we do not print all the time
args = ["-P{x}", "{filename}"]
msg = "sending '{filename}' to printer '{x}'"
x = "kyo_einseitig"
